# Site settings
title: Anebi Agbo's CV
description: Anebi's CV
favicon: /assets/img/avatar.JPG
baseurl: https://github.com/An3bi/resumecard
url: https://github.com/An3bi/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Anebi Agbo
  title: BI Developer
  address: Tempe, Arizona
  email: Anebi13@gmail.com
  link: http://An3bi.me
  weibo:
  github: An3bi
  linkedin: anebiBenjamin
  twitter: Higherarch
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Early Warning Services LLC
      location: Scottsdale, Arizona
      title: BI Analyst
      started: 2017
      duration: (May 2017 - Present)
      description: Wrangling data and providing Zelle operational intelligence
    - work2:
      company: Trax Technologies
      location: Scottsdale, Arizona
      title: Tableau Support Engineer
      started: 2016
      duration: (2016 - 2017)
      description: Tableau Performance tuning and administration
    - work3:
      company: TAPFIN
      location: Tempe, Arizona
      title: Data Analyst
      started: 2016
      duration: (2016 - 2016)
      description: 3 month SAP fieldglass data recon project, Data mapping between SAP and SQL databases.
    - work4:
      company: CSAA Insurance Group
      location: Glendale, Arizona
      title: Data Analyst
      started: 2016
      duration: (2016 - 2016)
      description: 3 month data integrity contract data recon project, Data mapping between Oracle and Cognos.

  educationHistory:

    - education1:
      organization: Northern Arizona University
      location: Flagstaff, Arizona
      degree: Bachelor
      major: Computer Information Technology
      started: 2017
      duration: (2017 - 2018)
      description: CIT program with a focus on sharpening programming Skills and learning the nuances of IT management.

      - education2:
        organization: Rio Salado College
        location: Tempe, Arizona
        Qualification: Certificate of Computer Usage and Applications
        major: Information Technology
        started: 2015
        duration: (2015 - 2016)
        description: Focused on learning the basics of web development and Information Technology.

        - education3:
          Favorite learning Platforms: PluralSight, Lynda, DataCamp,IBM Cognitive.AI
          Goal: Programming Skills
          description: IT skills are constantly evolving and technology improves frequently. In a bid to
          keep my skills sharp, I am constantly learning and applying new skills.

          - education2:
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: Idoma
      proficiency: Professional
    - language3:
      name: Creole Pidgin (English based)
      proficiency: Native
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 70%
    - skill2:
      name: Bootstrap
      percentage: 55%
    - skill3:
      name: D3.js
      percentage: 40%
    - skill4:
      name: SQL
      percentage: 65%
    - skill5:
      name: Python
      percentage: 35%
